# Automatically generated by Pynguin.
import densenet as module_0


# Wrong input types for parameters input_shape and nb_classes.
def test_case_0():
    int_0 = -4944
    float_0 = 71.3
    tuple_0 = ()
    dict_0 = {float_0: int_0, int_0: tuple_0, float_0: float_0}
    tuple_1 = int_0, dict_0
    int_1 = 756
    float_1 = -470.107996
    var_0 = module_0.DenseNet(tuple_1, int_1, int_1, int_1, float_1)
    assert var_0 is None
