# Automatically generated by Pynguin.
import densenet as module_0


# def test_case_0():
#     set_0 = None
#     dict_0 = {set_0: set_0}
#     int_0 = 1258
#     tuple_0 = int_0,
#     list_0 = [int_0, dict_0, tuple_0]
#     float_0 = -608.70235
#     var_0 = module_0.convolution_block(tuple_0, list_0, tuple_0, float_0)
#     assert var_0 is None


# def test_case_1():
#     set_0 = set()
#     list_0 = [set_0]
#     var_0 = module_0.convolution_block(list_0, list_0)
